name: bennu_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  riverpod: ^1.0.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.0
  firebase_core:
  firebase_auth:
  firebase_storage:
  firebase_messaging:
  firebase_analytics:
  firebase_crashlytics:
  flutter_local_notifications:
  sqflite:
  passkeys: ^1.0.2
  flutter_secure_storage:
  flutter_stripe: 
  qr_flutter:
  http: ^1.1.4
  flutter_riverpod: ^1.0.3+1
  url_launcher:
  fake_cloud_firestore: ^2.4.1+1
  video_player: ^2.7.1
  visibility_detector: ^0.4.0+2
  solana: ^0.30.0
  image_picker: ^1.0.4
  hooks_riverpod:

dependency_overrides:
  http: ^0.13.3



dev_dependencies:
  mockito: ^5.0.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true